name: React Native CI
on:
  workflow_dispatch:
  push:
    tags:
      - '*'

jobs:
  android-build:
    name: Android Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup JDK
        uses: actions/setup-java@v1.4.3
        with:
          java-version: 11

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Restore node_modules from cache
        uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Cache Gradle Wrapper
        uses: actions/cache@v2
        with:
          path: ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-wrapper-${{ hashFiles('**/android/gradle/wrapper/gradle-wrapper.properties') }}

      - name: Cache Gradle Dependencies
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/android/build.gradle') }}
          restore-keys: |
            ${{ runner.os }}-gradle-caches-

      - name: Make Gradlew executable
        run: cd android && chmod +x ./gradlew

      - name: Build Android
        run: |
          cd android && ./gradlew assembleRelease --no-daemon --info 2>&1 | tee build-log.txt

      - name: Rename APK
        run: |
          mkdir downloads
          cd android
          mv app/build/outputs/apk/release/*.apk ../downloads/kaoo-app.apk
          mv build-log.txt ../downloads/build-log.txt

      - name: Upload APK as artifact
        uses: actions/upload-artifact@v2
        with:
          name: kaoo-app
          path: downloads

      - name: Create Release
        id: create_release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: false
          files: downloads/kaoo-app.apk
